# Generated by Django 4.2.7 on 2024-08-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_quizattempt_answer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('student', 'quiz')},
        ),
    ]
