# Generated by Django 4.2.7 on 2024-08-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_quizattempt_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='min_avg_score',
            field=models.FloatField(default=35.0),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='min_completed_modules',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
