# Generated by Django 4.2.7 on 2024-08-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_certificatetemplate_min_avg_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='min_completed_modules',
        ),
    ]
