# Generated by Django 4.2.7 on 2024-08-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_certificatetemplate_min_completed_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
